config/routes.rb
Rails.application.routes.draw do
  root 'resources#index'

  post '/resources/create', to: 'resources#create', as: 'resources_create'
  get '/url/:short_url', to: 'resources#bounce', as: 'resources_bounce'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/resource.rb
class Resource < ApplicationRecord
  before_create :add_short_url

  validates :long_url, presence: true
  validates :short_url, length: { maximum: 16 } 

  private
    def add_short_url
      if self.short_url == ""
        self.short_url = SecureRandom.hex(4)
      else
        self.short_url = self.short_url.parameterize(separator: '_')
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @resources = Resource.all
  end

end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  def index
    @resources = Resource.all.order(created_at: :desc).page params[:page]
  end

  def create
    @resource = Resource.new(resource_params);

    if @resource.save
      @resources = Resource.all.order(created_at: :desc).page params[:page]
      render partial: "resources", locals: { resources: @resources }, notice: 'URL successfully shortened.'
    else
      redirect_to :index, status: :unprocessable_entity
    end
  end

  def bounce
    @resource = Resource.find_by_short_url(params["short_url"])
    @resource.update(clicked: @resource.clicked + 1);
    redirect_to @resource.long_url, allow_other_host: true
  end

  private

    def resource_params
      params.permit(:long_url, :short_url)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
</head>
<body class="min-h-full pt-12 md:pt-20 pb-6 px-2 md:px-0" style="font-family:'Lato',sans-serif;">
    <div class="mycontent">
        <%= yield %>
    </div>
    <div class="box">
        <div class='wave -one'></div>
        <div class='wave -two'></div>
        <div class='wave -three'></div>
    </div>

</body>
</html>

app/views/pages/_resources.html.erb
<%= turbo_frame_tag "researchers" do %>

  <div class="flex flex-col container max-w-xl mt-10 mx-auto w-full items-center justify-center bg-white dark:bg-gray-800">
    <ul class="flex flex-col divide-y w-full">
      <% @resources.each do |resource| %>
        <li class="flex flex-row">
          <div class="select-none cursor-pointer hover:bg-gray-50 flex flex-1 items-center p-4">
            <div class="flex-1 pl-1">
              <%= link_to resource.long_url, class: "font-medium dark:text-white", target: "_blank", data: { turbo_frame: "_top"} %>
              <div class="text-gray-600 dark:text-gray-200 text-sm">Count: <%= resource.clicked %></div>
            </div>
            <div class="flex flex-row justify-center">
              <div class="text-gray-600 dark:text-gray-200 text-xs">6:00 AM</div>
              <button class="w-10 text-right flex justify-end">
                <svg width="20" fill="currentColor" height="20" class="hover:text-gray-800 dark:hover:text-white dark:text-gray-200 text-gray-500" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                  <path d="M1363 877l-742 742q-19 19-45 19t-45-19l-166-166q-19-19-19-45t19-45l531-531-531-531q-19-19-19-45t19-45l166-166q19-19 45-19t45 19l742 742q19 19 19 45t-19 45z"></path>
                </svg>
              </button>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/resources/_resources.html.erb
<%= turbo_frame_tag "resources" do %>

  <div class="flex flex-col container max-w-3xl mt-10 mx-auto w-full items-center justify-center bg-white" data-controller="clipboard">
    <ul class="flex flex-col divide-y w-full">
      <% @resources.each do |resource| %>
        <li class="flex flex-row flex-wrap">
          <div class="select-none cursor-pointer hover:bg-gray-50 grow flex flex-1 items-center p-4 flex-col lg:flex-row md:flex-row sm:flex-col">
            <div class="flex-1 pl-1">
              <%= link_to resource.long_url, class: "font-medium", target: "_blank", data: { turbo_frame: "_top"} %>
              <div class="text-gray-600 text-sm">Count: <%= resource.clicked %></div>
            </div>
            <div class="flex flex-row justify-center items-center gap-2">
              <%= link_to "#{resources_bounce_url(resource.short_url)}", "/url/#{url_for(resource.short_url)}", data: { turbo_frame: "_top"}, target: "_blank", class: "text-purple-600 text-sm" %>

              <button data-clipboard-shorturl-param="<%= resources_bounce_url(resource.short_url)%>" data-action="clipboard#copyText" class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold text-sm hover:text-white py-1 px-2  border border-blue-500 hover:border-transparent active:bg-slate-700 rounded-full">
                Copy
              </button>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
    <%= paginate @resources %>
  </div>
<% end %>

app/views/resources/index.html.erb
    <header class="max-w-lg mx-auto">
        <a href="/">
            <h1 class="text-4xl font-bold text-white text-center">URL_Shortener</h1>
        </a>
    </header>

    <main class="bg-white max-w-3xl mx-auto p-8 md:p-12 my-10 shadow-2xl">
        <section>
            <h3 class="font-bold text-2xl">Welcome to URL_Shortener</h3>
            <p class="text-gray-600 pt-2">Paste the original url here.</p>
        </section>

        <% if notice.present? %>
            <div class="flex items-center bg-purple-500 text-white text-sm font-bold px-4 py-3 my-6" role="alert">
            <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
            <p><%= notice %></p>
            </div>
        <% end %>

        <section class="mt-10">
          <%= form_with url: "resources/create", method: :post, data: { turbo_frame: "resources", controller: "alias" } do |form| %>
            <div class="flex items-stretch mt-5">
                <%= form.url_field :long_url, class: " bg-gray-50 rounded-r-none text-base leading-none text-gray-800 p-2 w-4/5 border border-gray-300 focus:outline-none focus:border-gray-500", placeholder: "Longer url .. ", required: true %>
                <button type="button" data-action="alias#toggleAlias" class="cursor-pointer rounded-l-none hover:bg-blue-600 bg-blue-700 text-xs font-medium leading-none text-white p-2 uppercase focus:ring-slate-700">custom</button>
                <%= form.submit "shorten", class: "w-32 cursor-pointer rounded-l-none hover:bg-indigo-600 bg-indigo-700 text-xs font-medium leading-none text-white p-2 uppercase focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-700" %>
            </div>
            <div class="flex mt-2" data-alias-target="shorturlWrapper">
                <span class="inline-flex items-center px-3 text-sm text-gray-800 bg-slate-200">
                    <%= "#{request.host_with_port}/url/" %>
                </span>
                <%= form.text_field :short_url, class: "rounded-none bg-gray-50 border border-gray-300 text-gray-900 focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm p-2", placeholder: "alias", maxlength: 16, data: { "alias-target": "shorturlInput" } %>
            </div>
          <% end %>
        </section>

        <%= render "resources", resources: @resources %>
    </main>

    <footer class="max-w-xl mx-auto flex justify-center text-white">
        <a href="https://www.linkedin.com/in/wuletaw-wonte" target="_blank" class="hover:underline">Contact</a>
        <span class="mx-3">•</span>
        <a href="https://github.com/wuletawwonte/url-shortener" target="_blank" class="hover:underline">Github</a>
    </footer>